steps:
### Building Docker Image for gp2-browser-app ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/precision-med-app:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/precision-med-app:${_IMAGE_TAG_PRECISION_APP}', '-f', 'microservices/precision_med_api/frontend/app/Dockerfile', 'microservices/precision_med_api/frontend/app/' ]
  id: 'create docker image for precision-med-app'

### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for precision-med-app'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/precision-med-app:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/precision-med-app:${_IMAGE_TAG_PRECISION_APP}
### Building Docker Image for gp2-browser-app ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/gp2-browser:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/gp2-browser:${_IMAGE_TAG_GP2_BROWSER}', '-f', 'apps/gp2-browser/Dockerfile', 'apps/gp2-browser/' ]
  id: 'create docker image for gp2-browser-app'

### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for gp2-browser-app'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/gp2-browser:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/gp2-browser:${_IMAGE_TAG_GP2_BROWSER}
          
### Building Docker Image for genotracker-app ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/genotracker-app:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/genotracker-app:${_IMAGE_TAG_GTRACKER_APP}', '-f', 'apps/genotracker/Dockerfile', 'apps/genotracker/' ]
  id: 'create docker image for genotracker-app'


### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for genotracker-app'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/genotracker-app:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_APPS_REPO}/genotracker-app:${_IMAGE_TAG_GTRACKER_APP}


#### Building Docker Image for genotracker-api ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_API_REPO}/genotracker-api:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_API_REPO}/genotracker-api:${_IMAGE_TAG_GTRACKER_API}', '-f', 'microservices/genotracker/Dockerfile', 'microservices/genotracker/' ]
  id: 'create docker image for genotracker-api'



#### Pushing Docker Image for genotracker-api ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for genotracker-api'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_API_REPO}/genotracker-api:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_API_REPO}/genotracker-api:${_IMAGE_TAG_GTRACKER_API}



#### Building Docker Image for genotools-api ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_API_REPO}/genotools-api:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_API_REPO}/genotools-api:${_IMAGE_TAG_GTOOLS_API}', '-f', 'microservices/genotools-api/Dockerfile', 'microservices/genotools-api/' ]
  id: 'create docker image for genotools-api'



#### Pushing Docker Image for genotracker-api ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for genotools-api'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_API_REPO}/genotools-api:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_API_REPO}/genotools-api:${_IMAGE_TAG_GTOOLS_API}



#### Building Docker Image for gtprecheck-api ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_WORKFLOW_REPO}/idat-ped-bed-merge:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_WORKFLOW_REPO}/idat-ped-bed-merge:${_IMAGE_TAG_IDAT_PED_BED_MERGE_WF}', '-f', 'workflows/idat-ped-bed-merge/Dockerfile', 'workflows/idat-ped-bed-merge/' ]
  id: 'create docker image for Workflow idat-ped-bed-merge'


#### Pushing Docker Image for genotracker-api ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for  Workflow idat-ped-bed-merge'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_WORKFLOW_REPO}/idat-ped-bed-merge:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_WORKFLOW_REPO}/idat-ped-bed-merge:${_IMAGE_TAG_IDAT_PED_BED_MERGE_WF}

## update values.yaml for dev, staging and prod helm charts with the new image tags
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'update apps and apis SHA in deployments/helm-charts/dev'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git -b ${_CD_BRANCH}
    echo "Updating image tag version ..."
    cd genotools-server/deployments/helm-charts/dev
    sed "s|GOOGLE_CLOUD_PROJECT|${PROJECT_ID}|g; \
    s|GKE_CLUSTER_NAME|${_GKE_CLUSTER_NAME}|g;
    s|precision-med-app:COMMIT_SHA|precision-med-app:${SHORT_SHA}|g;
    s|genotracker-app:COMMIT_SHA|genotracker-app:${SHORT_SHA}|g;
    s|genotracker-api:COMMIT_SHA|genotracker-api:${SHORT_SHA}|g;
    s|genotools-api:COMMIT_SHA|genotools-api:${SHORT_SHA}|g;
    s|gp2-browser:COMMIT_SHA|gp2-browser:${SHORT_SHA}|g" \
    values.yaml.tpl> values.yaml
    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "syedislamuddin"
    git config --global user.email "islamuddinn@yahoo.com"
    git add -A
    git commit -m "[Cloud Builder] Updated image tag europe-west4.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO} for all apps/apis from commits ${COMMIT_SHA} etc in dev folder"
    git push --no-thin https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git ${_CD_BRANCH}

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'update workflow SHA in apps/gke-manager/deployment/workflow/helm'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git -b ${_CD_BRANCH}
    echo "Updating image tag version ..."
    cd genotools-server/apps/gke-manager/deployments/workflow
    sed "s|GOOGLE_CLOUD_PROJECT|${PROJECT_ID}|g; \
    s|idat-ped-bed-merge:COMMIT_SHA|idat-ped-bed-merge:${SHORT_SHA}|g" \
    idat-ped-bed-merge-values.yaml.tpl> idat-ped-bed-merge-values.yaml
    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "syedislamuddin"
    git config --global user.email "islamuddinn@yahoo.com"
    git add -A
    git commit -m "[Cloud Builder] Updated image tag europe-west4.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO} for all workflow from commits ${COMMIT_SHA} etc"
    git push --no-thin https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git ${_CD_BRANCH}


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/github-access-token/versions/latest
    env: 'GIT_ACCESS_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY

