

steps:
### Building Docker Image for gp2-browser-app ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/gp2-browser-app:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/gp2-browser-app:${_IMAGE_TAG_GP2_BROWSER}', '-f', 'apps/gp2-browser/Dockerfile', 'apps/gp2-browser/' ]
  id: 'create docker image for gp2-browser-app'

# - name: 'gcr.io/cloud-builders/gcloud'
#   id: 'save SHA for later use 1'
#   args: ['bash', '-c', 'echo $SHORT_SHA > /workspace/gp2browser_sha.txt']



### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for gp2-browser-app'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/gp2-browser-app:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/gp2-browser-app:${_IMAGE_TAG_GP2_BROWSER}
    
- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      'echo $SHORT_SHA > /workspace/gp2browser_sha.txt'
      
### Building Docker Image for genotracker-app ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotracker-app:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotracker-app:${_IMAGE_TAG_GTRACKER_APP}', '-f', 'apps/genotracker/Dockerfile', 'apps/genotracker/' ]
  id: 'create docker image for genotracker-app'

# - name: 'gcr.io/cloud-builders/gcloud'
#   id: 'save SHA for later use 2'  
#   args: ['bash', '-c', 'echo $SHORT_SHA > /workspace/gtracker-app_sha.txt']
#   # env:
#   #   - 'SHORT_SHA_GENOTRACKER_APP=$SHORT_SHA'


### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for genotracker-app'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotracker-app:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotracker-app:${_IMAGE_TAG_GTRACKER_APP}

  
- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      'echo $SHORT_SHA > /workspace/gtracker-app_sha.txt'
#       export SHORT_SHA_GENOTRACKER_APP=$SHORT_SHA
#       echo "Saving SHORT_SHA to shared file..."
#       echo "SHORT_SHA_GENOTRACKER_APP=$SHORT_SHA" >> /workspace/vars.env


#### Building Docker Image for genotracker-api ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotracker-api:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotracker-api:${_IMAGE_TAG_GTRACKER_API}', '-f', 'microservices/genotracker/Dockerfile', 'microservices/genotracker/' ]
  id: 'create docker image for genotracker-api'

# - name: 'gcr.io/cloud-builders/gcloud'
#   id: 'save SHA for later use 3'  
#   args: ['bash', '-c', 'echo $SHORT_SHA > /workspace/gtracker-api_sha.txt']
  # env:
  #   - 'SHORT_SHA_GENOTRACKER_API=$SHORT_SHA'


#### Pushing Docker Image for genotracker-api ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for genotracker-api'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotracker-api:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotracker-api:${_IMAGE_TAG_GTRACKER_API}

- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      'echo $SHORT_SHA > /workspace/gtracker-api_sha.txt'
#       export SHORT_SHA_GENOTRACKER_API=$SHORT_SHA
#       echo "Saving SHORT_SHA to shared file..."
#       echo "SHORT_SHA_GENOTRACKER_API=$SHORT_SHA" >> /workspace/vars.env


#### Building Docker Image for genotools-api ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotools-api:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotools-api:${_IMAGE_TAG_GTOOLS_API}', '-f', 'microservices/genotools-api/Dockerfile', 'microservices/genotools-api/' ]
  id: 'create docker image for genotools-api'

# - name: 'gcr.io/cloud-builders/gcloud'
#   id: 'save SHA for later use 4'  
#   args: ['bash', '-c', 'echo $SHORT_SHA > /workspace/genotools-api_sha.txt']
  # env:
  #   - 'SHORT_SHA_GENOTOOLS_API=$SHORT_SHA'


#### Pushing Docker Image for genotracker-api ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for genotools-api'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotools-api:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genotools-api:${_IMAGE_TAG_GTOOLS_API}

- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      'echo $SHORT_SHA > /workspace/genotools-api_sha.txt'
#       export SHORT_SHA_GENOTOOLS_API=$SHORT_SHA
#       echo "Saving SHORT_SHA to shared file..."
#       echo "SHORT_SHA_GENOTOOLS_API=$SHORT_SHA" >> /workspace/vars.env


#### Building Docker Image for gtprecheck-api ####
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/gtprecheck-api:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/gtprecheck-api:${_IMAGE_TAG_GTPRECHECK_API}', '-f', 'microservices/gt-precheck/Dockerfile', 'microservices/gt-precheck/' ]
  id: 'create docker image for gtprecheck-api'

# - name: 'gcr.io/cloud-builders/gcloud'
#   id: 'save SHA for later use 5'
#   args: ['bash', '-c', 'echo $SHORT_SHA > /workspace/gtprecheck-api_sha.txt']
  # env:
  #   - 'SHORT_SHA_GTPRECHECK_API=$SHORT_SHA'

#### Pushing Docker Image for genotracker-api ####
- name: 'gcr.io/cloud-builders/docker'
  id: 'push docker image for gtprecheck-api'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/gtprecheck-api:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/gtprecheck-api:${_IMAGE_TAG_GTPRECHECK_API}

- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      'echo $SHORT_SHA > /workspace/gtprecheck-api_sha.txt'
#       export SHORT_SHA_GTPRECHECK_API=$SHORT_SHA
#       echo "Saving SHORT_SHA to shared file..."
#       echo "SHORT_SHA_GTPRECHECK_API=$SHORT_SHA" >> /workspace/vars.env

# - name: 'bash'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       echo ${SHORT_SHA_GP2_BROWSER_APP}
#       echo "Reading from shared file..."
#       source /workspace/vars.env
#       echo "SHA hash: $SHORT_SHA_GTPRECHECK_API"
#       echo "SHA has: $SHORT_SHA_GENOTOOLS_API"
      

## update values.yaml
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'update gp2-browser-app SHA in helm-charts dev'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git -b ${_CD_BRANCH}
    echo "Updating image tag version ..."
    cd genotools-server/deployments/helm-charts/dev
    sed "s/GOOGLE_CLOUD_PROJECT/$PROJECT_ID/g" values.yaml.tpl | \
    sed "s/gp2-browser-app:COMMIT_SHA/gp2-browser-app:$(cat /workspace/gp2browser_sha.txt)/g" | \
    sed "s/genotracker-app:COMMIT_SHA/genotracker-app:$(cat /workspace/gtracker-app_sha.txt)/g" | \ 
    sed "s/genotracker-api:COMMIT_SHA/genotracker-api:$(cat /workspace/gtracker-api_sha.txt)/g" | \ 
    sed "s/genotools-api:COMMIT_SHA/genotools-api:$(cat /workspace/genotools-api_sha.txt)/g" | \ 
    sed "s/gtprecheck-api:COMMIT_SHA/gtprecheck-api:$(cat /workspace/gtprecheck-api_sha.txt)/g" > values.yaml
    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "syedislamuddin"
    git config --global user.email "islamuddinn@yahoo.com"
    git add -A
    git commit -m "[Cloud Builder] Updated image tag europe-west4.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO} for all apps/apis from commits ${COMMIT_SHA} etc in dev folder"
    git push --no-thin https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git ${_CD_BRANCH}

# - name: 'gcr.io/cloud-builders/gcloud'
#   id: 'update gp2-browser-app SHA in helm-charts staging'
#   entrypoint: /bin/sh
#   secretEnv: ['GIT_ACCESS_TOKEN']
#   args:
#   - '-c'
#   - |
#     git clone https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git -b ${_CD_BRANCH}
#     echo "Updating image tag version ..."
#     cd genotools-server/deployments/helm-charts/staging
#     sed "s/GOOGLE_CLOUD_PROJECT/$PROJECT_ID/g" values.yaml.tpl | \
#     sed "s/gp2-browser-app:COMMIT_SHA/gp2-browser-app:$SHORT_SHA_GP2_BROWSER_APP/g" | \
#     sed "s/genotracker-app:COMMIT_SHA/genotracker-app:$SHORT_SHA_GENOTRACKER_APP/g" | \ 
#     sed "s/genotracker-api:COMMIT_SHA/genotracker-api:$SHORT_SHA_GENOTRACKER_API/g" | \ 
#     sed "s/genotools-api:COMMIT_SHA/genotools-api:$SHORT_SHA_GENOTOOLS_API/g" | \ 
#     sed "s/gtprecheck-api:COMMIT_SHA/gtprecheck-api:$SHORT_SHA_GTPRECHECK_API/g" > values.yaml
#     echo "Pushing changes to k8s manifest repo ..."
#     git config --global user.name "syedislamuddin"
#     git config --global user.email "islamuddinn@yahoo.com"
#     git add -A
#     git commit -m "[Cloud Builder] Updated image tag europe-west4.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO} for all apps from commits ${COMMIT_SHA} etc in staging folder"
#     git push --no-thin https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git ${_CD_BRANCH}

# - name: 'gcr.io/cloud-builders/gcloud'
#   id: 'update gp2-browser-app SHA in helm-charts prod'
#   entrypoint: /bin/sh
#   secretEnv: ['GIT_ACCESS_TOKEN']
#   args:
#   - '-c'
#   - |
#     git clone https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git -b ${_CD_BRANCH}
#     echo "Updating image tag version ..."
#     cd genotools-server/deployments/helm-charts/prod
#     sed "s/GOOGLE_CLOUD_PROJECT/$PROJECT_ID/g" values.yaml.tpl | \
#     sed "s/gp2-browser-app:COMMIT_SHA/gp2-browser-app:$SHORT_SHA_GP2_BROWSER_APP/g" | \
#     sed "s/genotracker-app:COMMIT_SHA/genotracker-app:$SHORT_SHA_GENOTRACKER_APP/g" | \ 
#     sed "s/genotracker-api:COMMIT_SHA/genotracker-api:$SHORT_SHA_GENOTRACKER_API/g" | \ 
#     sed "s/genotools-api:COMMIT_SHA/genotools-api:$SHORT_SHA_GENOTOOLS_API/g" | \ 
#     sed "s/gtprecheck-api:COMMIT_SHA/gtprecheck-api:$SHORT_SHA_GTPRECHECK_API/g" > values.yaml
#     echo "Pushing changes to k8s manifest repo ..."
#     git config --global user.name "syedislamuddin"
#     git config --global user.email "islamuddinn@yahoo.com"
#     git add -A
#     git commit -m "[Cloud Builder] Updated image tag europe-west4.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO} for all apps/apis from commits ${COMMIT_SHA} etc in prod folder"
#     git push --no-thin https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/datatecnica/genotools-server.git ${_CD_BRANCH}


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/github-access-token/versions/latest
    env: 'GIT_ACCESS_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
