# for ssl certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sslRelated.sec }} #gtserver-ssl
  #namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""  