apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.microservices.gtPrecheckAPI.podName }}
  name: {{ .Values.microservices.gtPrecheckAPI.podName }}
  namespace: {{ .Values.namespace }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.microservices.gtPrecheckAPI.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.microservices.gtPrecheckAPI.podName }}
      annotations:
        gke-gcsfuse/volumes: "true" 
        #Optional resource configuration for the sidecar container. Allocate more CPU to the sidecar container if your workloads need higher throughput.
        gke-gcsfuse/cpu-limit: "2"
        gke-gcsfuse/memory-limit: "8Gi"
        gke-gcsfuse/ephemeral-storage-limit: "8Gi"
    spec:
      serviceAccountName: {{ .Values.ksaBucket }}
      containers:
      - image: {{ .Values.microservices.gtPrecheckAPI.image }}
        name: gtprecheck-container
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: gcs-volume
          mountPath: {{ .Values.microservices.gtPrecheckAPI.mountPath }}
          readOnly: false
      volumes:
      - name: gcs-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVOLUMECLAIM }}  
          readOnly: false
    
      # Ensure pods are scheduled on nodes with the specified GCP VM type
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodePools.gtPrecheckApiNodePool }} 
