# issuer-lets-encrypt-production.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.sslRelated.caIssuer }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: syed@datatecnica.com # ❗ Replace this with your email address
    profile: tlsserver
    privateKeySecretRef:
      name: {{ .Values.sslRelated.caIssuer }}
    solvers:
    - http01:
        ingress:
          name: {{ .Values.ingressName }} 


# kubectl get ClusterIssuer
# kubectl describe issuers.cert-manager.io letsencrypt-staging
