apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appservices.gp2browserApp.iapSec }}
  namespace: {{ .Values.namespace }}
type: Opaque 
data:
  stringData:
  client_id: NjY0NzIyMDYxNDYwLW5nMzZ1ZGxqM2MxOGs0a2dnb2wxOWc5YWkwaWphcWtuLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
  client_secret: R09DU1BYLWNnNkN4V3VTRk41S1MzUXNybGp2LWYtVl9odmoK
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appservices.genotrackerApp.iapSec }}
  namespace: {{ .Values.namespace }}
type: Opaque 
data:
  stringData:
  client_id: NjY0NzIyMDYxNDYwLWIxcDRjYWpjdHFnZXIwMzE3NjU2bjF2NzVqdjcwOWhqLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  client_secret: R09DU1BYLU1Qdjl4VTJNek9aLVQ2ZjdWbDZFYUFaemxFYXQ=
---
# for ssl certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sslRelated.sec }} #gtserver-ssl
  #namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""  