apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.gcpSecretManager.externalSecretName }} 
  namespace: {{ .Values.namespace }}
spec:
#   refreshInterval: 10s            # rate SecretManager pulls GCPSM, Low refereshInternval for demo purpose,Set this value based based on apps
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.gcpSecretManager.secretStoreName }}   # name of the ClusterSecretStore or you can also reference SecretStore
  target:
    name: {{ .Values.gcpSecretManager.kubernetesSecretName }}   # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract: 
      key: gtserver-related    #get all keys from the GCPSM secret


#get secret gtserver-secrets  -o jsonpath='{.data.GENOTOOLS_API_KEY}' | base64 -d
#kubectl get secret db-creds -n $K8S_NAMESPACE  -o jsonpath='{.data.db-user}' | base64 -d
#kubectl get secret db-creds -n $K8S_NAMESPACE  -o jsonpath='{.data.db-pass}' | base64 -d
